name: Self-Triggering Lottery Draw

on:
  workflow_dispatch:
    inputs:
      next_run_time:
        description: 'Next run time (ISO format)'
        required: false
        default: ''

jobs:
  trigger-draw:
    runs-on: ubuntu-latest
    
    steps:
    - name: Process Draw and Schedule Next Run
      run: |
        echo "🎯 Starting self-triggering draw detection at $(date)"
        
        # Process the draw (same logic as before)
        echo "🔗 Connecting to: https://${{ secrets.REPLIT_URL }}"
        RESPONSE=$(curl -s -X POST \
          "https://${{ secrets.REPLIT_URL }}/api/automated-draw-trigger" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.DRAW_TRIGGER_SECRET }}" \
          -d '{"source": "github-self-trigger", "timestamp": "'$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)'"}' \
          || echo '{"success": false, "message": "Connection failed"}')
        
        echo "📡 Response: $RESPONSE"
        
        # Calculate next run time (12:00 AM GMT+4 tomorrow = 20:00 UTC)
        NEXT_RUN=$(date -u -d "tomorrow 20:00" +%Y-%m-%dT%H:%M:%S.%3NZ)
        echo "⏰ Next scheduled run: $NEXT_RUN"
        
        # Schedule the next run using GitHub API
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/self-trigger.yml/dispatches" \
          -d '{"ref": "main", "inputs": {"next_run_time": "'$NEXT_RUN'"}}'
        
        echo "✅ Next run scheduled for tomorrow at 12:00 AM GMT+4"
